version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    depends_on:
      - db

  # ... другие сервисы ... (добавьте аналогичные описания для остальных сервисов)

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Aspirine1
      - POSTGRES_DB=dance_studio
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data